"""empty message

Revision ID: 5a67ac552aa4
Revises: cc783e0f19d8
Create Date: 2025-04-26 22:51:06.893355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a67ac552aa4'
down_revision = 'cc783e0f19d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('monto_pagado', sa.Float(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['socio_id'], ['socio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('historia_pagos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historia_pagos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('socio_id', sa.INTEGER(), nullable=False),
    sa.Column('monto_pagado', sa.FLOAT(), nullable=False),
    sa.Column('fecha_pago', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['socio_id'], ['socio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('historial_pagos')
    # ### end Alembic commands ###
