"""creacion de tablas

Revision ID: 99cfc64e833d
Revises: ea77c5a6d364
Create Date: 2025-04-17 22:43:14.839476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99cfc64e833d'
down_revision = 'ea77c5a6d364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asamblea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_asamblea', sa.Date(), nullable=True),
    sa.Column('asistentes_asamblea', sa.String(length=50), nullable=False),
    sa.Column('acta_asamblea', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deudas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['socio_id'], ['socio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deuda_id', sa.Integer(), nullable=False),
    sa.Column('monto_pagado', sa.Float(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['deuda_id'], ['deudas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_pagos')
    op.drop_table('deudas')
    op.drop_table('asamblea')
    # ### end Alembic commands ###
