"""init

Revision ID: cc783e0f19d8
Revises: 
Create Date: 2025-04-26 22:50:23.855906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc783e0f19d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asamblea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_asamblea', sa.Date(), nullable=True),
    sa.Column('asistentes_asamblea', sa.String(length=50), nullable=False),
    sa.Column('acta_asamblea', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('socio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('celular', sa.String(length=9), nullable=False),
    sa.Column('correo_electronico', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celular'),
    sa.UniqueConstraint('correo_electronico')
    )
    op.create_table('deudas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['socio_id'], ['socio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historia_pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socio_id', sa.Integer(), nullable=False),
    sa.Column('monto_pagado', sa.Float(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['socio_id'], ['socio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historia_pagos')
    op.drop_table('deudas')
    op.drop_table('socio')
    op.drop_table('asamblea')
    # ### end Alembic commands ###
